// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {zededa} from '../models';

export function AddRecentDevice(arg1:string):Promise<void>;

export function ConnectToNode(arg1:string):Promise<string>;

export function DisableSSH(arg1:string):Promise<void>;

export function GetDeviceServices(arg1:string):Promise<string>;

export function GetSSHStatus(arg1:string):Promise<main.SSHStatus>;

export function GetSettings():Promise<config.Config>;

export function ResetEdgeView(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SearchNodes(arg1:string):Promise<Array<zededa.Node>>;

export function SetupSSH(arg1:string):Promise<void>;
