// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentDevice(arg1) {
  return window['go']['main']['App']['AddRecentDevice'](arg1);
}

export function ConnectToNode(arg1) {
  return window['go']['main']['App']['ConnectToNode'](arg1);
}

export function DisableSSH(arg1) {
  return window['go']['main']['App']['DisableSSH'](arg1);
}

export function GetDeviceServices(arg1) {
  return window['go']['main']['App']['GetDeviceServices'](arg1);
}

export function GetSSHStatus(arg1) {
  return window['go']['main']['App']['GetSSHStatus'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ResetEdgeView(arg1) {
  return window['go']['main']['App']['ResetEdgeView'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SearchNodes(arg1) {
  return window['go']['main']['App']['SearchNodes'](arg1);
}

export function SetupSSH(arg1) {
  return window['go']['main']['App']['SetupSSH'](arg1);
}
